env:
  browser: true
  es2021: true
  jquery: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
    semi: ["error", "always"],
    node/no-callback-literal: "off"
}