name: Auto labeller for pull requests

on: pull_request_review
jobs:
  label:
    runs-on: ubuntu-latest
    name: Label when approved
    steps:
      - name: Prebuilt action for approval labelling
        uses: pullreminders/label-when-approved-action@master
        env: 
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          ADD_LABEL: "Approved"
