name: Auto approver-merger
on:
  # Run for any PR reviews, allow manual run
  pull_request_review:
  workflow_dispatch:
jobs:
  # "Label and Merge"" job runs the powershell script I made
  label-and-merge:
    runs-on: windows-latest
    name: Auto labeller-merger, based off user approvals
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: GitHub API based script
        env:
          APPROVALS: 3
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        shell: pwsh
        run: |
          .\.github\workflows\script.ps1
